/// AI Insight Entity.
/// Represents an AI-generated advisory message for the student.
/// 
/// Layer: Domain
/// Responsibility: Explainable AI recommendations and mentorship.
/// Inputs: Generated by AI mentor service based on student data.
/// Outputs: Displayed on AI Mentor screen, dashboard tips.
library;

class AIInsight {
  final String id;
  final InsightType type;
  final String title;
  final String message;
  final String reasoning; // Why AI generated this insight
  final InsightPriority priority;
  final String? actionLabel; // Optional CTA
  final String? actionRoute; // Navigation destination
  final DateTime generatedAt;
  final bool isRead;

  const AIInsight({
    required this.id,
    required this.type,
    required this.title,
    required this.message,
    required this.reasoning,
    required this.priority,
    this.actionLabel,
    this.actionRoute,
    required this.generatedAt,
    this.isRead = false,
  });

  AIInsight markAsRead() {
    return AIInsight(
      id: id,
      type: type,
      title: title,
      message: message,
      reasoning: reasoning,
      priority: priority,
      actionLabel: actionLabel,
      actionRoute: actionRoute,
      generatedAt: generatedAt,
      isRead: true,
    );
  }
}

enum InsightType {
  encouragement, // Positive reinforcement
  warning, // Risk alert
  suggestion, // Study recommendation
  milestone, // Achievement recognition
  reminder, // Deadline or schedule reminder
}

enum InsightPriority {
  low,
  medium,
  high,
}
