/// Study Task Entity.
/// Represents a single task in the AI-generated study plan.
/// 
/// Layer: Domain
/// Responsibility: Individual actionable study item with AI reasoning.
/// Inputs: Generated by StudyPlannerService based on knowledge gaps.
/// Outputs: Displayed in dashboard, tracked for completion.
library;

class StudyTask {
  final String id;
  final String subjectId;
  final String? topicId;
  final String title;
  final String description;
  final int estimatedMinutes;
  final TaskPriority priority;
  final TaskType type;
  final DateTime scheduledDate;
  final DateTime? completedAt;
  final String aiReasoning; // Why AI recommended this task

  const StudyTask({
    required this.id,
    required this.subjectId,
    this.topicId,
    required this.title,
    required this.description,
    required this.estimatedMinutes,
    required this.priority,
    required this.type,
    required this.scheduledDate,
    this.completedAt,
    required this.aiReasoning,
  });

  bool get isCompleted => completedAt != null;

  StudyTask copyWith({
    String? id,
    String? subjectId,
    String? topicId,
    String? title,
    String? description,
    int? estimatedMinutes,
    TaskPriority? priority,
    TaskType? type,
    DateTime? scheduledDate,
    DateTime? completedAt,
    String? aiReasoning,
  }) {
    return StudyTask(
      id: id ?? this.id,
      subjectId: subjectId ?? this.subjectId,
      topicId: topicId ?? this.topicId,
      title: title ?? this.title,
      description: description ?? this.description,
      estimatedMinutes: estimatedMinutes ?? this.estimatedMinutes,
      priority: priority ?? this.priority,
      type: type ?? this.type,
      scheduledDate: scheduledDate ?? this.scheduledDate,
      completedAt: completedAt ?? this.completedAt,
      aiReasoning: aiReasoning ?? this.aiReasoning,
    );
  }
}

enum TaskPriority {
  critical, // Must complete today
  high, // Important this week
  medium, // Should complete
  low, // Optional enhancement
}

enum TaskType {
  review, // Review previously learned material
  learn, // Learn new concepts
  practice, // Practice problems/exercises
  quiz, // Take adaptive quiz
  revise, // Pre-exam revision
}
