/// Study Plan Entity.
/// Represents a weekly AI-generated study plan with reasoning.
///
/// Layer: Domain
/// Responsibility: Aggregates study tasks with AI explanation.
/// Inputs: Generated by StudyPlannerService.
/// Outputs: Displayed on dashboard, drives daily recommendations.
library;

import 'package:studnet_ai_buddy/domain/entities/study_task.dart';

class StudyPlan {
  final String id;
  final DateTime weekStartDate;
  final DateTime weekEndDate;
  final List<StudyTask> tasks;
  final String aiSummary; // AI's overview of the week's focus
  final List<String> keyObjectives; // Main goals for the week
  final DateTime generatedAt;

  const StudyPlan({
    required this.id,
    required this.weekStartDate,
    required this.weekEndDate,
    required this.tasks,
    required this.aiSummary,
    required this.keyObjectives,
    required this.generatedAt,
  });

  /// Returns tasks for a specific date.
  /// Returns tasks for a specific date.
  List<StudyTask> tasksForDate(DateTime date) {
    return tasks.where((task) {
      final taskDate = task.date.toLocal();
      return taskDate.year == date.year &&
          taskDate.month == date.month &&
          taskDate.day == date.day;
    }).toList();
  }

  StudyPlan copyWith({
    String? id,
    DateTime? weekStartDate,
    DateTime? weekEndDate,
    List<StudyTask>? tasks,
    String? aiSummary,
    List<String>? keyObjectives,
    DateTime? generatedAt,
  }) {
    return StudyPlan(
      id: id ?? this.id,
      weekStartDate: weekStartDate ?? this.weekStartDate,
      weekEndDate: weekEndDate ?? this.weekEndDate,
      tasks: tasks ?? this.tasks,
      aiSummary: aiSummary ?? this.aiSummary,
      keyObjectives: keyObjectives ?? this.keyObjectives,
      generatedAt: generatedAt ?? this.generatedAt,
    );
  }

  /// Returns completion percentage.
  double get completionRate {
    if (tasks.isEmpty) return 0.0;
    final completed = tasks.where((t) => t.isCompleted).length;
    return completed / tasks.length;
  }

  /// Returns total estimated study time in minutes.
  int get totalEstimatedMinutes {
    return tasks.fold(0, (sum, task) => sum + task.estimatedMinutes);
  }
}
