// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeiqrIFi02yUGFc12T4MZ59sOq4JXMvd0',
    appId: '1:679903159402:web:29aac7b912bdfd542a9613',
    messagingSenderId: '679903159402',
    projectId: 'studnet-ai-buddy',
    authDomain: 'studnet-ai-buddy.firebaseapp.com',
    storageBucket: 'studnet-ai-buddy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZrKLasZtS6gZAdbplbBNIdFPM6PBp2XU',
    appId: '1:679903159402:android:ffa7e1b6488db7692a9613',
    messagingSenderId: '679903159402',
    projectId: 'studnet-ai-buddy',
    storageBucket: 'studnet-ai-buddy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPXMRH7LHGATqnp9Ti-7DHwAkP3RX772c',
    appId: '1:679903159402:ios:9f8007d31280de3e2a9613',
    messagingSenderId: '679903159402',
    projectId: 'studnet-ai-buddy',
    storageBucket: 'studnet-ai-buddy.firebasestorage.app',
    iosBundleId: 'com.example.studnetAiBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPXMRH7LHGATqnp9Ti-7DHwAkP3RX772c',
    appId: '1:679903159402:ios:9f8007d31280de3e2a9613',
    messagingSenderId: '679903159402',
    projectId: 'studnet-ai-buddy',
    storageBucket: 'studnet-ai-buddy.firebasestorage.app',
    iosBundleId: 'com.example.studnetAiBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeiqrIFi02yUGFc12T4MZ59sOq4JXMvd0',
    appId: '1:679903159402:web:0ae3238037e1b7322a9613',
    messagingSenderId: '679903159402',
    projectId: 'studnet-ai-buddy',
    authDomain: 'studnet-ai-buddy.firebaseapp.com',
    storageBucket: 'studnet-ai-buddy.firebasestorage.app',
  );
}
